# -*- coding: utf-8 -*-
"""task 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILr9mU3M-_Ie9NSV6FkttB_XZYtwFXeL
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
# %matplotlib inline

pd.set_option('display.max_columns', 200)

from google.colab import files
uploaded = files.upload()

# Load file (train.csv)
import io
df = pd.read_csv(io.BytesIO(uploaded['train.csv']))
df.head()

df.shape

df.info()

df.describe(include="all")

df.describe(include="all")

missing = df.isnull().sum().sort_values(ascending=False)
missing_percent = (df.isnull().mean()*100).sort_values(ascending=False)

pd.DataFrame({
    'Missing_Count': missing,
    'Missing_%': missing_percent
})

num_cols = ['Age','Fare','SibSp','Parch']

for col in num_cols:
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    sns.histplot(df[col].dropna(), kde=True)
    plt.title(f"Histogram: {col}")

    plt.subplot(1,2,2)
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot: {col}")

    plt.show()

cat_cols = ['Survived','Pclass','Sex','Embarked']

for col in cat_cols:
    print(df[col].value_counts())
    sns.countplot(x=df[col])
    plt.title(f"Count of {col}")
    plt.show()

for col in ['Sex', 'Pclass', 'Embarked']:
    print(f"\nSurvival vs {col}")
    print(pd.crosstab(df[col], df['Survived'], normalize='index'))
    sns.countplot(x=col, hue='Survived', data=df)
    plt.show()

plt.figure(figsize=(8,5))
sns.kdeplot(data=df, x='Age', hue='Survived')
plt.title("Age Distribution by Survival")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='Survived', y='Fare', data=df)
plt.title("Fare vs Survival")
plt.show()

sns.pairplot(df[['Survived','Pclass','Age','SibSp','Parch','Fare']].dropna(),
             hue='Survived',
             diag_kind='kde')
plt.show()



plt.figure(figsize=(10,7))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

df2 = df.copy()

df2['Embarked'].fillna(df2['Embarked'].mode()[0], inplace=True)
df2['HasCabin'] = df2['Cabin'].notnull().astype(int)
df2['CabinDeck'] = df2['Cabin'].fillna('X').str[0]

df2['Title'] = df2['Name'].str.extract(r',\s*([^\.]+)\.')

df2['Age'] = df2['Age'].fillna(df2['Age'].median())

df2['Fare'] = df2['Fare'].fillna(df2['Fare'].median())

df2 = pd.get_dummies(df2, columns=['Sex','Embarked','Title','CabinDeck'], drop_first=True)

df2.head()

df.to_csv("cleaned_titanic.csv", index=False)
files.download("cleaned_titanic.csv")

"""This heatmap visualizes the correlation matrix of the numerical columns in the DataFrame. The color intensity and value in each cell represent the correlation coefficient between two variables. A value close to 1 indicates a strong positive correlation, close to -1 indicates a strong negative correlation, and close to 0 indicates a weak or no linear correlation."""